apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: "#{aks.letsencrypt.email}#"
    server: "#{aks.letsencrypt.server}#"
    preferredChain: "DST Root CA X3"
    privateKeySecretRef:
      name: letsencrypt-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers: 
    - dns01:
        azureDNS:
          clientID: "#{aks.letsencrypt.azuredns.clientid}#"
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
          subscriptionID: "#{aks.letsencrypt.azuredns.subscriptionid}#"
          tenantID: "#{aks.letsencrypt.azuredns.tenantid}#"
          resourceGroupName: "#{aks.letsencrypt.azuredns.resourcegroupname}#"
          hostedZoneName: "#{aks.letsencrypt.azuredns.hostedzonename}#"
          environment: AzurePublicCloud
